version: '3.8'

services:
  node-red:
    image: nodered/node-red:latest
            
    depends_on:
      - influxdb
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped


  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2  # Corrigez le chemin pour v2
    environment:
      - INFLUXDB_v2_TOKEN=qRFZysV4tibMYwxvG2LO7uJPwo4l4CCI4bbewqAfRpxNyzs3bsobYMY-HDhYdXS_4PeLqYAKQ32POuGLEfnBkQ==  # Token pour l'auth (utilisez-le dans Node-RED)
      - INFLUXDB_v2_ORG=myorg
      - INFLUXDB_v2_BUCKET=mybucket
      - INFLUXDB_v2_ADMIN_USER=my-user
      - INFLUXDB_v2_ADMIN_PASSWORD=my-password
    restart: unless-stopped
    
  

volumes:
  node_red_data:
  influxdb_data: